### PR TITLE
added roll ball game

### PR DESCRIPTION
**Pull request by Sudhee-bsp**
#### Just added a new game.
rollball

### CODE REVIEW

**Comment by Sudhee-bsp** [comment]
@n-ce , Please review my PR. Thank you.

**Review by n-ce — CHANGES_REQUESTED** [review]
It looks awesome but still some requirements are necessary.
- Use id's or classes ([ Naming Scheme ](https://github.com/n-ce/Bromage/blob/main/Modules/Modules.md#what-should-my-html-file-contain)) instead of raw tags to refer the elements in both the script & styles.
- Instead of styling the body tag, wrap a div around your entire html and give it the id body then style #body.
- Why are these necessary?
  - If not implemented properly these conflict with the main scripts and styles of Bromage, that's why.

**Comment by Sudhee-bsp** [comment]
Sure, I'll make the requested changes.

**Comment by n-ce** [comment]
Great work, thank you! Going to merge right away. Also for touch devices we need a virtual buttons rather than keyboard one's, are you willing to work on that? If yes, I'll be opening up an issue and assign you right away.

**Review by n-ce — APPROVED** [review]

**Comment by Sudhee-bsp** [comment]
@n-ce 
#### Following changes were made:-

- [x] inserted ID to all raw tags and made sure nowhere a raw tag is used, both in HTML & script files.
- [x] Increased canvas height & width also, for making big the game screen😁
- [x] Also wrapped the whole tags in a div - named as ID #body, as suggested.


Waiting to review my PR & merge soon. Also requesting to add hacktoberfest 2021 label if possible. Thank you.

**Comment by Sudhee-bsp** [comment]
Great🎉🎉

**Comment by n-ce** [comment]
I have added the hacktober fest label to the former issue, should I add it to the repo as well?

**Comment by Sudhee-bsp** [comment]
Please add it to this PR under labels, that would be fine I guess.

**Comment by n-ce** [comment]
@Sudhee-bsp https://github.com/n-ce/Bromage/issues/9 Because I can't test it on my phone and I don't have PC xD

**Comment by Sudhee-bsp** [comment]
@n-ce Hi, sorry to bother you. Could you please also add the **Hacktoberfest-accepted** label to this PR.
Because this didn't get counted towards my progress.
Thanks!

**Pull request merged**
