### PR TITLE
Designed Weather API

### LINKED ISSUE #5: Add weather info to homepage
Using a Free API , implement weather data to show on [Home.html](https://github.com/n-ce/SPACE/blob/main/Modules/Home.html)
To Javascript must be included in [Home.js](https://github.com/n-ce/SPACE/blob/main/Modules/Home.js)

### PR DESCRIPTION
**Pull request by JanviRaina**
replace the appid in Home.js first with your api key.

### CODE REVIEW

**Review by n-ce — CHANGES_REQUESTED** [review]
-  You should not be removing the previous code.
- This is a module not a website, there should be no header, body tag or script tags.
-  Use your own CSS in place of bootstrap, if not do not implement any styles.
 - Use pure JavaScript instead of jquery.
 - Use a free API that does not require an APIkey as mentioned in the issue.

**Comment by n-ce** [comment]
OMG @JanviRaina you're a Genius, Thank you! I'll merge right away!

**Review by n-ce — APPROVED** [review]

**Comment by n-ce** [comment]
Oh no there is still an issue it's not working, are you sure the script was tested?
[Check.](https://n-ce.github.io/Bromage)

**Comment by JanviRaina** [comment]
Yes I've checked it.
But I still have a script tag there in Home.html which is calling the
Home.js file.
Let me know if it doesn't work.

**Comment by n-ce** [comment]
> Yes I've checked it. But I still have a script tag there in Home.html which is calling the Home.js file. Let me know if it doesn't work.

Actually there is no need to call the file as it gets called in the main script file of the page, hence the quotes api loads just fine even without the script tag at home.html.

**Comment by JanviRaina** [comment]
Ok,I had this confusion.
Is it working right now?

**Comment by n-ce** [comment]
No no,  it is not, can you take a look please?

**Comment by JanviRaina** [comment]
Yes I just tried opened Home.html in my browser, a location access popup comes and then on allowing ,it displays the weather.

**Comment by n-ce** [comment]
I am on the chrome for Android browser, unfortunately I'm not getting any prompts for location permission. :(

**Comment by n-ce** [comment]
Ok I'm getting the prompt now by removing the load listener https://github.com/n-ce/Bromage/commit/21f3c89b7744e8560c2e9fe798d23f8b2e821129
But I wonder why its still not getting updated.
Edit : well here's the problem
`Cannot set properties of null (setting 'textContent')
at <anonymous>:25:33`

**Comment by n-ce** [comment]
It's fixed now https://github.com/n-ce/Bromage/commit/84f2f27a0aeaf62f08b10b40cc457f780f0af0c5 thanks again!

**Pull request merged**
